# Generated by Django 5.1.4 on 2024-12-19 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(default='https://via.placeholder.com/256x256.png', upload_to='icon/')),
                ('description', models.TextField(blank=True, default='', max_length=1024)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('is_banned', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'bot'), name='unique_group_bot')],
            },
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('is_banned', models.BooleanField(default=False)),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='unique_group_user')],
            },
        ),
    ]
