# Generated by Django 5.1.4 on 2024-12-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(default='https://placehold.com/256x256.png', upload_to='group/icon/'),
        ),
    ]
