# Generated by Django 5.1.4 on 2024-12-19 05:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('icon', models.ImageField(default='https://via.placeholder.com/256x256.png', upload_to='icon/')),
                ('about', models.TextField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(default='619b6d0ce70e817166314d67c9753e5e75847011b15f1559261faac614fd845b73128a2f3a66abb25f5704e9ade25f96fe5af1f45384a62bf121d0264a7967499156008fbe825b9c997909e545ce55c59d95647afd603c0d69938c95fe44af318e981047150b15ae5cb7ecd5a5f9d44066d92de3f007a4d542eb965db91cc61e', max_length=128)),
                ('token_salt', models.CharField(default='37fe4dc071e6654ec13e8924da1690f325b6a4ecb23504207624482ec329107d8eff184da2963191f9d6876e5120f33e70efeb4f952e640c65f64bb5dcaeb3dab21c1acabd66095de3f1ccf9f3c08c6ecaf38e825a5c59608478e0dedac2afc958e0f01bc8db71445e3ee5def1d9aa184cc661f2d650b2ee0959e2867333b38b', max_length=128)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
