# Generated by Django 5.1.4 on 2024-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='token_hash',
            field=models.CharField(default='9c731e7a3364a5ddc3cfc52a36a18536d49953a2b0dde33ac10011733737a0723923168577436c9ea11e7790667ab5ccdd99ef3f169bcc85b600d1110eaa3f8ebdcf4efaac07198e301806e6b962ddab1cef84a039a779ce16446c102b24ce6f3cf8a7cfc3905d39ba49f68ef80c0a0831bd61d16899489c42c9d2d77d4be763', max_length=128),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token_salt',
            field=models.CharField(default='c5264336610aeb1494eaac3c4007a15890eee4b44a9deafca64bfde23a85a1090fdbce5148fb72f07024008152384c0ef012a00665eac09a7817b8f36a90fa0d0cbe6f6c47042934d0acca6f0c14eb95291ad0e4d707b5380f24805b32af347e23c26ffcb25b9d02339a93b21eca1224b4e23ebef6da4b5d491b507348abbc35', max_length=128),
        ),
    ]
