# Generated by Django 5.1.4 on 2024-12-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userotp_token_hash_alter_userotp_token_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='token_hash',
            field=models.CharField(default='278a6aef7d48a9306b6eadf251b8e73816f56e3224157a753cc0d835c4218b3a7757cb2a2e53ed1c43df88d05a96fbe6a9fd2136e75889a4e786312a8cad2b3fc302a9b4739f7076275d13f609e56e0e7eb7bfee42e14c0202d057260fa09105ed6bac7193926317c398b703bfda47957ead7c3b778565fbd7b2c50ca8de75c0', max_length=128),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token_salt',
            field=models.CharField(default='6274c211ad7d6f483c17c6c21f08dab1252e30f2e3ee3188a6bd6f17ec4738be296cb8f612656d62764ac7f57e58d5983cdc52c5d53654e7bbbd6b0c6c4714f613eee6ea7e837b9dd013f825133e8e714a360228e2eadaac919eed691e3f167cf7290cc156372d0862fe9da6b2d62d8ac688de6a359267114cf8b2a042364e07', max_length=128),
        ),
    ]
