# Generated by Django 5.1.4 on 2024-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userotp_token_hash_alter_userotp_token_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='token_hash',
            field=models.CharField(default='4b6599f967cc9a594ac58eefc328c03e6b459bf85b1991aa7ab3096a079564cf508abd8ed954909ae80b57aaff0b79a3646af04afabe3c8792debf7cca73c87d93bb58c9d78b40d1b47e21ff4f729547ada7a200735f19d89e8b7665f55bca22f24ad2c44c073bd80bfda2052cc9655a5b0f29d6e970ab156b08ecfa0ecedc44', max_length=128),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token_salt',
            field=models.CharField(default='bd37d5639bf145a07aa8f11c1c2aa56846f36f293c6268e905d85dff54d6aab9c58023608475626d1f075e562169860c64bcb9e615a2a0b94723f6d6609dd2f73d6ea5bc59742104d1066f9f70f36aa34eb89f644edd25abdbe4d4143ba4ee61c5483b0ec359c5247b8d476bfca091867e8ec37a2136d712db09552f1207e00c', max_length=128),
        ),
    ]
