# Generated by Django 5.1.4 on 2024-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userotp_token_hash_alter_userotp_token_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='token_hash',
            field=models.CharField(default='b35ce51fde34f3b1cc654bbbd0b2a843244dbe5c0a370b8dbf72035b0d01741a79f31ded2c4ffbadf65a7fa09696e2da48b2afef6903d587097e892d160d1fb6cd4ed5cde48c564925015a578cb6655157fc66d8fee1d4fbf272620d2453a56e6d2f013309d69f265bf6cad09f83446f7d04aea07f17c7100cd3fd545c0fb905', max_length=128),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token_salt',
            field=models.CharField(default='23643a7906e7aca6eb85e1b4a16ba6bf83e46223089dd500319b59bc1685f3ac0f96e56bb69b5e00aabd4ea52d26b4afc8ae425c3ba3b047a89bf95b1030aa2c6fb2f3e3254b2b7e225f97517c4e7ef53758314dd996ea5e37a2ed8263f5e6d7867adfe2c28875bafb5f5f30d17b435a6af72df266c2be961602af3a609901e8', max_length=128),
        ),
    ]
