# Generated by Django 5.1.4 on 2024-12-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userotp_token_hash_alter_userotp_token_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='token_hash',
            field=models.CharField(default='ba7a28f7f9ff6895d867c5e6e2018df51c1fc90abea44f29fccf4445303678ead1525923fb577ed6c8ab35aa2e2c9b9b95f5d41544089d13a724d6244fa019226f433e3f67a0c7559b981be4101a730b8b0b075ed198031879b121762793fbb589b8be0bd9d57fdaf23b77335be6b41e06e3c307e37ad8b15c9f601a0e034d7c', max_length=128),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token_salt',
            field=models.CharField(default='4e49b25a96d593902e2599f123a9140d017e2f779b3798a2ddc937cb16252289d39edcc7ca4abe7f039ed782bdd9d40c736f81710fcc23c8a47081bc728811b9cca18fafca24ee9d0dfea87548ddef5214160a22e96d967a1f8496f7599f11c92039e9ccf12dd6374873c4e914ee3ca7a72796231bea5cac253a353cb299686c', max_length=128),
        ),
    ]
