# Generated by Django 5.1.4 on 2024-12-19 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debate', '0001_initial'),
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='debateuser',
            name='debate',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='debate.debate'),
        ),
        migrations.AddField(
            model_name='debateuser',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debatemessage',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='debate.debateuser'),
        ),
        migrations.AddConstraint(
            model_name='debateuser',
            constraint=models.UniqueConstraint(fields=('user', 'debate'), name='unique_user_debate'),
        ),
    ]
